---
- name: this Playbook for stoping Cognos
  hosts: 192.168.1.171



  tasks:


    - name: Wait for VMs to be reachable
      wait_for:
        host: 192.168.1.171
        port:  5985 
        delay: 5
        timeout: 60
      register: reachability_result
      ignore_errors: yes


    - name: Display the result
      ansible.builtin.debug:
        msg: "{{ reachability_result }}"



